### ISSUE TITLE
Fuzzing: panic in dhcp4r, index 240 out of range

### ISSUE THREAD

**Issue by kpcyrd** [kpcyrd/sniffglue#16]
```
$ RUST_BACKTRACE=1 cargo run --example read_packet 'CgoAAP//QDj//wAACAAKCgAAAAAAGRERERERNScAAAoACgBDAEQ1NTU1JwAACgAKAAD//wA4//8AAAgACgo='
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/read_packet CgoAAP//QDj//wAACAAKCgAAAAAAGRERERERNScAAAoACgBDAEQ1NTU1JwAACgAKAAD//wA4//8AAAgACgo=`
[10, 10, 0, 0, 255, 255, 64, 56, 255, 255, 0, 0, 8, 0, 10, 10, 0, 0, 0, 0, 0, 25, 17, 17, 17, 17, 17, 53, 39, 0, 0, 10, 0, 10, 0, 67, 0, 68, 53, 53, 53, 53, 39, 0, 0, 10, 0, 10, 0, 0, 255, 255, 0, 56, 255, 255, 0, 0, 8, 0, 10, 10]
thread 'main' panicked at 'index 240 out of range for slice of length 20', /checkout/src/libcore/slice/mod.rs:748:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::slice::slice_index_len_fail
             at /checkout/src/libcore/slice/mod.rs:748
  10: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
             at /checkout/src/libcore/slice/mod.rs:879
  11: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /checkout/src/libcore/slice/mod.rs:730
  12: dhcp4r::packet::decode
             at /XXXX/.cargo/registry/src/github.com-1ecc6299db9ec823/dhcp4r-0.1.0/src/packet.rs:22
  13: sniffglue::centrifuge::dhcp::extract
             at src/centrifuge/dhcp.rs:52
  14: sniffglue::centrifuge::udp::extract
             at src/centrifuge/udp.rs:25
  15: sniffglue::centrifuge::parse
             at src/centrifuge/mod.rs:31
  16: read_packet::main
             at examples/read_packet.rs:11
  17: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  18: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  19: main
  20: __libc_start_main
  21: _start
```

**Comment by krolaw** [comment]
Hi, thanks for the testing.  In short, decode requires packets to be 240 bytes or greater - I agree, it should check for this.
